##
## Copyright 2023 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: Merge CC reports

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check files in artifacts
        working-directory: ${{ github.workspace }}
        run: |
          for i in $(seq 1 500); do
            sleep 10
            [ -f "$HOME/cc-reporter/cc-test-reporter/main-coverage.json" -a -f "$HOME/cc-reporter/cc-test-reporter/c2d-coverage.json"] && break
            done
          ls -la "$HOME/cc/artifacts/"
      - uses: actions/download-artifact@v2
        with:
          name: cc-report
          path: $HOME/cc-reporter/cc-test-reporter

      - name: Calculate coverage
        working-directory: ${{ github.workspace }}
        run: |
          FILES_COUNT=`ls -1 $HOME/cc-reporter/cc-test-reporter | wc -l | tr -d ' '`
          ./cc-reporter/cc-test-reporter sum-coverage --output - --parts $FILES_COUNT $HOME/cc-reporter/cc-test-reporter/*.json | ./cc-reporter/cc-test-reporter upload-coverage --input -
