##
## Copyright 2023 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: Merge CC reports

on:
  workflow_run:
    workflows: [ "Provider tests", "Provider tests for C2D" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve and merge coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-reports
          path: merged-coverage
      - name: Merge coverage reports
        run: |
          coverage combine merged-coverage
      - name: Calculate total coverage
        run: |
          coverage report -m --include=ocean_provider/*

      - name: Get coverage percentage
        id: coverage
        run: |
          total_coverage=$(coverage report --include=ocean_provider/* --fail-under=80 -m | grep TOTAL | awk '{print $NF}')
          echo "Coverage: $total_coverage"
          echo "::set-output name=coverage::$total_coverage"
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: b0d75c25d5176c59e8ea665bf74396d9ee1bdf2c97f11ccc6869f9e91d80a6c7